apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: allotsys-com-tls
spec:
  secretName: allotsys-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: allotsys.com
  dnsNames:
    - allotsys.com
    - www.allotsys.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - allotsys.com
          - www.allotsys.com